// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  inputField: string;
  root: string;
  search: string;
  text: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
